### ISSUE TITLE
Support for Pixel

### ISSUE THREAD

**Issue by mizzunet** [affggh/opsplash#1]
Would you be so kind to make support for Pixel's splash.img?

Here's one taken from Pixel 4A https://0x0.st/odF_.img

This is my terminal output
```
		[OPPO SPLASH MODIFIED TOOL]
=---------------------------------------------------------------=
	AUTHOR:	affggh 	VERSION:	1.1 
=---------------------------------------------------------------=
File input : 	[../splash.img
]Dir output : 	[pic]
		[OPPO SPLASH MODIFIED TOOL]
=---------------------------------------------------------------=
	AUTHOR:	affggh 	VERSION:	1.1 
=---------------------------------------------------------------=
[WARNNING]: Fake header magic read failed, this may not a issue.
[WARNNING]: Read fake magic faild, this may not a issue.
[INFO]: Checking header magic...
[ERROR]: Failed
Real header magic check failed, this may not a oppo splash image.
[ERROR]: Read real header failed, please comfirm this is a oppo splash image!
METADATA:
	meta1:
	meta2:
	meta3:
Image number:	0
Unknow flag:	0
Device width:	0
Device height:	0
Compressed flag:	0
[INFO]: Extracting...
	OFFSET	REALSZ	COMPSZ	NAME
=---------------------------------------------------------------=
=---------------------------------------------------------------=
[SUCCESS]: Done!
```
But nothing on pic folder

**Comment by affggh** [comment]
> Would you be so kind to make support for Pixel's splash.img?
> 
> Here's one taken from Pixel 4A https://0x0.st/odF_.img
> 
> This is my terminal output
> 
> ```
> 		[OPPO SPLASH MODIFIED TOOL]
> =---------------------------------------------------------------=
> 	AUTHOR:	affggh 	VERSION:	1.1 
> =---------------------------------------------------------------=
> File input : 	[../splash.img
> ]Dir output : 	[pic]
> 		[OPPO SPLASH MODIFIED TOOL]
> =---------------------------------------------------------------=
> 	AUTHOR:	affggh 	VERSION:	1.1 
> =---------------------------------------------------------------=
> [WARNNING]: Fake header magic read failed, this may not a issue.
> [WARNNING]: Read fake magic faild, this may not a issue.
> [INFO]: Checking header magic...
> [ERROR]: Failed
> Real header magic check failed, this may not a oppo splash image.
> [ERROR]: Read real header failed, please comfirm this is a oppo splash image!
> METADATA:
> 	meta1:
> 	meta2:
> 	meta3:
> Image number:	0
> Unknow flag:	0
> Device width:	0
> Device height:	0
> Compressed flag:	0
> [INFO]: Extracting...
> 	OFFSET	REALSZ	COMPSZ	NAME
> =---------------------------------------------------------------=
> =---------------------------------------------------------------=
> [SUCCESS]: Done!
> ```
> 
> But nothing on pic folder

Its only support oppo/realme/oneplus snapdragon device，not support pixel，and i cant download your link， can you change to google drive or else

**Comment by mizzunet** [comment]
Here's different link https://oshi.at/SFkZ

**Comment by affggh** [comment]
> Here's different link https://oshi.at/SFkZ

this two links i download is a 32kb empty file

**Comment by mizzunet** [comment]
That is what I get by `dd if=/dev/block/by-name/splash of=/sdcard/splash`

Other blocks
```
/dev/block/by-name/                                                     <
ALIGN_TO_128K_1  cmnlib_b     keymaster_b  qupfw_b  tz_b
ALIGN_TO_128K_2  ddr          keystore     sda      uefisecapp_a
abl_a            devcfg_a     klog         sdb      uefisecapp_b
abl_b            devcfg_b     limits       sdc      uefivarstore
aop_a            devinfo      logfs        sdd      userdata
aop_b            dtbo_a       metadata     sde      vbmeta_a
apdp_a           dtbo_b       misc         sdf      vbmeta_b
apdp_b           frp          modem_a      secdata  vbmeta_system_a
boot_a           fsc          modem_b      splash   vbmeta_system_b
boot_b           fsg          modemst1     spunvm   xbl_a
cdt              hyp_a        modemst2     ssd      xbl_b
cdt_backup       hyp_b        msadp_a      storsec  xbl_config_a
cmnlib64_a       imagefv_a    msadp_b      super    xbl_config_b
cmnlib64_b       imagefv_b    persist      toolsfv
cmnlib_a         keymaster_a  qupfw_a      tz_a
```
