### ISSUE TITLE
Unable to read logo.img from oneplus 8

### ISSUE THREAD

**Issue by joshuah345** [affggh/opsplash#2]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/29195927/210615139-90092623-e03c-4385-8f6d-95961596e605.png">

[logo.img link](https://x0.at/uHuL.img)

**Comment by affggh** [comment]
This image is oppo rle format, not opsplash format. maybe I will make another tool to change it.

**Comment by joshuah345** [comment]
Okay, thank you. hope to see a tool soon.
