### ISSUE TITLE
OnePlus6T support

### ISSUE THREAD

**Issue by WalleoAndrew** [affggh/opsplash#3]
我从我的Oneplus6T提取的splash.img无法读取，以下是输出
![image](https://github.com/affggh/opsplash/assets/91959052/a057f293-0631-40c7-9f00-76ef42fb3f0f)

**Comment by affggh** [comment]
> 我找到了一个工具，来源于XDA：https://forum.xda-developers.com/t/tool-mod-op6t-splash-screen-modification-linux.3874158/

大哥，一加8以上才能用啊，6t之前的xda有别的工具，格式也不是gz是rle😭
